substitutions:
  device: watch
  name: Watch
  comment: "DEV"
  
esphome:
  name: mcu-${device}
  comment: ${comment}

esp32:
  board: esp32doit-devkit-v1
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: 6.5.0

packages:
  common: !include common/common.yaml