esphome:
  name: esphome-web-4602b8

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-4602B8"
    password: "JN8YBLZSZjyR"



captive_portal:

web_server:
  port: 80

sensor:
- platform: uptime
  name: Uptime Sensor

- platform: wifi_signal
  name: "WiFi Signal Sensor"
  update_interval: 60s

i2s_audio: 
- id: i2s_in
  i2s_lrclk_pin: GPIO26
  i2s_bclk_pin: GPIO25