substitutions:
  name: everything-presence-lite-xxxxxx
  friendly_name: 'Everything Presence Lite'
  
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password