substitutions:
  device: fireplace-old
  name: Heating Fireplace
  comment: "OBSOLETE | Ground floor, Kitchen: Fireplace monitoring for heating"

esphome:
  name: mcu-${device}
  comment: ${comment}
  platform: ESP8266
  board: esp01_1m

# wifi:
#   use_address: mcu-fireplace.local

packages:
  common: !include common/common.yaml

dallas:
  - pin: 4

binary_sensor:
  - platform: template
    name: "${name} Fire"
    lambda: |-
      if (id(heating_fireplace_temperature).state > 37.5) {
        return true;
      } else {
        return false;
      }

sensor:
  - platform: dallas
    address: 0x6203168B32A7FF28
    # index: 0
    name: "${name}"
    id: 'heating_fireplace_temperature'
  - platform: dht
    pin: 14
    temperature:
      name: "Kitchen Temperature"
      id: 'kitchen_temperature'
    humidity:
      name: "Kitchen Humidity"
      id: 'kitchen_humidity'
    update_interval: 60s
    model: si7021
