substitutions:
  device: dev-temp
  name: Dev Temp
  comment: "DEV"
  
esphome:
  name: mcu-${device}
  comment: ${comment}

esp32:
  board: esp32doit-devkit-v1
  # framework:
  #   type: arduino
  #   # type: esp-idf

external_components:
  - source: components

packages:
  common: !include common/common.yaml

switch:
  - platform: gpio
    pin: GPIO27
    id: sensor_power
    restore_mode: ALWAYS_ON

dallas:
  - pin: GPIO25
    update_interval: 10s

sensor:
  - platform: dallas
    index: 0
    name: $name Dallas
    id: temp