esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "C/WOiMXnADdqmMWMOSt3TjE2OfvLKgykU6Jkem4CJXg="

ota:
  password: "71d15cd28c99fe71164f7f606c391123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "9UVFXZ8ufySW"

captive_portal:


sensor:
  - platform: bmi160
    address: 0x68
    update_interval: 60s
    acceleration_x:
      name: "BMI160 Accel X"
    acceleration_y:
      name: "BMI160 Accel Y"
    acceleration_z:
      name: "BMI160 Accel z"
    gyroscope_x:
      name: "BMI160 Gyro X"
    gyroscope_y:
      name: "BMI160 Gyro Y"
    gyroscope_z:
      name: "BMI160 Gyro z"
    temperature:
      name: "BMI160 Temperature"