---
<<: !include api.yaml
<<: !include ota.yaml
# <<: !include logger_debug.yaml
<<: !include ethernet.yaml

binary_sensor:
  - <<: !include binary_sensor/status.yaml

button:
  - <<: !include button/restart.yaml
  - <<: !include switch/safe_mode.yaml
  - <<: !include switch/shutdown.yaml

sensor:
  - <<: !include sensor/uptime.yaml
  # - <<: !include sensor/free_heap.yaml

#switch:
#  - <<: !include switch/restart.yaml
#  - <<: !include switch/safe_mode.yaml
#  - <<: !include switch/shutdown.yaml

text_sensor:
#  - <<: !include text_sensor/debug.yaml
  # - <<: !include text_sensor/version.yaml
  - <<: !include text_sensor/ethernet_info.yaml
