---
<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include logger.yaml

binary_sensor:
  - <<: !include binary_sensor/status.yaml

button:
  - <<: !include button/factory_reset.yaml
  - <<: !include button/restart.yaml
  - <<: !include button/safe_mode.yaml
  - <<: !include button/shutdown.yaml

sensor:
  - <<: !include sensor/uptime.yaml
  - <<: !include sensor/wifi_signal.yaml

text_sensor:
  - <<: !include text_sensor/version.yaml
  - <<: !include text_sensor/wifi_info.yaml

network:
  enable_ipv6: true